language: java
jdk:
#  - oraclejdk7
  - openjdk7
before_install:
#  - mvn install -Dmaven.javadoc.skip=true
- "echo skipped"
install:
#- "echo skipped"
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true
script:
- "echo skipped"
# - mvn clean install -Dmaven.javadoc.skip=true
# - mvn deploy
notifications:
  email:
    recipients:
    - asdfg2385856@gmail.com
    #on_success: [always|never|change]  default: change
    #on_failure: [always|never|change]  default: always
